name: Upload to Google Drive

on:
  workflow_dispatch:
    inputs:
      FILE_URL:
        description: "File url to push"
        required: true
      FILE_NAME:
        description: "Name for the file (optional)"
        required: false


jobs:
  Upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}

    steps:
      - name: Cleanup
        run: rm -rf ${{ github.workspace }}/*

      - name: Download the File
        run: |
          wget "${{ github.event.inputs.FILE_URL }}"

      - name: Naming
        run: |
          if [ -n "${{ github.event.inputs.FILE_NAME }}" ]; then
            mv "$(ls)" "${{ github.event.inputs.FILE_NAME }}"
            echo "FILE=${{ github.event.inputs.FILE_NAME }}" >> $GITHUB_ENV
          else
            FILE=$(ls)
            echo "FILE=$FILE" >> $GITHUB_ENV
          fi

      - name: google-drive-upload-git-action
        uses: adityak74/google-drive-upload-git-action@v0.3
        with:
          credentials: ${{ secrets.GSERVICE }}
          folderId: ${{ secrets.FOLDER_ID }}
          filename: ${{ env.FILE }}
          overwrite: "true"

